@baseUrl=http://localhost:5000

###
POST {{baseUrl}}/api/auth/register
Content-Type: application/json
 
{
    "name": "Petro",
    "surname": "Sota",
    "email": "petro@sota.com",
    "password":"ciao",
    "role":"user"
}

###

POST {{baseUrl}}/api/users/register-admin
Content-Type: application/json
 
{
    "name": "Petro",
    "surname": "Sota",
    "email": "petrosota@email.com",
    "password":"",
    "role":"admin"
}

###

POST {{baseUrl}}/api/auth/login
Content-Type: application/json
 
{
    "email": "ciao@gmail.com",
    "password":"ciaoo",
    "role":"user"
}

###

GET {{baseUrl}}/api/auth/me
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiI2NmZiY2I3ZWIxNTY2Y2Q0OWRkYWQxNGQiLCJpYXQiOjE3Mjc5ODA1NjQsImV4cCI6MTcyODAyMzc2NH0.xbDqwCSKFkUTwwPj-pg54AJfNNK5LRXg1h5zpXJFt14