@baseUrl=http://localhost:5000

###
POST {{baseUrl}}/api/auth/register
Content-Type: application/json
 
{
    "name": "Petro",
    "surname": "Sota",
    "email": "petro@sota.com",
    "password":"ciao",
    "role":"user"
}

###

POST {{baseUrl}}/api/users/register-admin
Content-Type: application/json
 
{
    "name": "Petro",
    "surname": "Sota",
    "email": "petrosota@email.com",
    "password":"",
    "role":"admin"
}

###

POST {{baseUrl}}/api/auth/login
Content-Type: application/json
 
{
    "email": "ciao@gmail.com",
    "password":"ciaoo",
    "role":"user"
}

###

GET {{baseUrl}}/api/auth/me
Authorization: Bearer your_token